---
- name: Testing andrewrothstein.go
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'go version'
      ansible.builtin.command: /usr/local/go/bin/go version
      changed_when: false
      register: go_test_output
    - name: Output from 'go version'
      ansible.builtin.debug:
        msg: '{{ go_test_output.stdout }}'
